### ISSUE TITLE
Java的Map可以做转换么

### ISSUE THREAD

**Issue by CarsarSky** [master-g/protoc-gen-bean#3]
你好 由于Protobuf底层的map是一个对象数组，现在转换的是一个对象数组，可以直接转换为Java的Map么

**Comment by master-g** [comment]
你好, 现在 protoc-gen-bean 仅支持输出 kotlin 格式, 请问你使用的是哪个分支?

**Comment by CarsarSky** [comment]
> 你好, 现在 protoc-gen-bean 仅支持输出 kotlin 格式, 请问你使用的是哪个分支?

抱歉才回复，我现在用的是deprecated-java。有可以支持Map转换的分支么

**Comment by master-g** [comment]
deprecated-java 分支已不再维护， 你可以使用 master 分支，现已支持 java 输出，请参阅 README 文档

**Comment by CarsarSky** [comment]
> deprecated-java 分支已不再维护， 你可以使用 master 分支，现已支持 java 输出，请参阅 README 文档

好的，那针对map的情况需要我自己开发是吧

**Comment by master-g** [comment]
> 好的，那针对map的情况需要我自己开发是吧

master 分支支持 map 和 oneof 的输出， 如果默认输出不符合你的具体要求，可以自行二次开发

**Comment by CarsarSky** [comment]
> 

> > 好的，那针对map的情况需要我自己开发是吧
> 
> master 分支支持 map 和 oneof 的输出， 如果默认输出不符合你的具体要求，可以自行二次开发

好的。感谢回复。我刚刚试了一下，master分支 map和oneof都不可以，
提示unable to find object with type named,
发现 调用extractUserImport的地方传错参数了，应该传入field不应该是valField. 然后看上下文发现那段代码好像用不到。

**Comment by master-g** [comment]
> 好的。感谢回复。我刚刚试了一下，master分支 map和oneof都不可以， 提示unable to find object with type named, 发现 调用extractUserImport的地方传错参数了，应该传入field不应该是valField. 然后看上下文发现那段代码好像用不到。

请问有导致错误的 proto 代码复现此问题吗？
